#!/bin/sh

set -e

# summary of how this script can be called:
#   * <prerm> `remove'
#   * <old-prerm> `upgrade' <new-version>
#   * <conflictor's-prerm> `remove` in-favour package <new-version>
#   * <deconfigured's-prerm> `deconfigure` in-favour package-being-installed version [removing conflicting-package version]
#   * <new-prerm> `failed-upgrade' <old-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package="minos-vnc-dummy"

case "${1}" in
  remove)
      if [ -f "/var/lib/dpkg/info/${package}.postinst" ]; then
          "/var/lib/dpkg/info/${package}.postinst" "${1}"
      fi
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear) : ;;

  *)
      printf "%s\\n" "${0} called with unknown argument \`${1}'" 1>&2
      exit 1
  ;;

esac

#DEBHELPER#

exit 0
